channels:
  - conda-forge # Primary channel
  - defaults
dependencies:
  # Python requirement
  - python>=3.8,<3.12

  # Core ML Dependencies (conda-forge will resolve CPU/GPU based on system)
  - pytorch>=2.6,<3
  - torchaudio>=2.6,<2.7
  - torchvision>=0.21,<0.22
  - pytorch-ignite>=0.5,<0.6

  # Other Dependencies
  - pyyaml>=6.0,<7.0
  - scikit-learn>=1.6,<1.7
  - matplotlib>=3
  - numpy>=2
  - wandb>=0.19,<1
  - tqdm>=4.67
  - pandas>=2.2,<3.0
  - pytest>=8.3,<9.0
  - pytest-mock>=3.14,<4.0
  # ffmpeg is required for torchaudio
  - ffmpeg<7.0
  - requests

  # - pip:
  #   - some-package-only-on-pypi
