site_name: EDANSA Bioacoustics Model
theme:
  name: material
  features:
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences

nav:
  - "Overview":
      - "Introduction": "index.md"
      - "Installation": "installation.md"
  - "Using the Pre-trained Model":
      - "Introduction": "using_pretrained_model/index.md"
      - "Providing Audio Data": "using_pretrained_model/providing_audio_data.md"
      - "Understanding Results": "using_pretrained_model/output_explanation.md"
      - "General Model Card (31m2plxv-V1)": "using_pretrained_model/model_card_general_31m2plxv-V1.md"
      - "Bird Species Model Card (ppq7zxqq)": "using_pretrained_model/model_card_bird_species_ppq7zxqq.md"
  - "Common Information":
      - "Troubleshooting": "common/troubleshooting.md"
